#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR


coffee -c ./lib/rules_core/source_references.coffee
# && \
# ./node_modules/coffee-script/bin/coffee -o . -c options.coffee
